
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yangy
 */
public class RoutingResourceGraph extends javax.swing.JFrame {

    /**
     * Creates new form RoutingResourceGraph
     */
    public RoutingResourceGraph() {
        ex = new RunGraph();
        squares = new JToggleButton[4][4];
        ex.initialize();
        initComponents();
        showCong();
        showGraph();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showPro = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        prosperity = new javax.swing.JTextArea();
        exitD = new javax.swing.JButton();
        graphPanel = new DrawGraph(ex,squares);
        route = new javax.swing.JButton();
        reroute = new javax.swing.JButton();
        showState = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        showPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        prosperity.setColumns(20);
        prosperity.setRows(5);
        jScrollPane1.setViewportView(prosperity);

        exitD.setText("OK");

        javax.swing.GroupLayout showProLayout = new javax.swing.GroupLayout(showPro.getContentPane());
        showPro.getContentPane().setLayout(showProLayout);
        showProLayout.setHorizontalGroup(
            showProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showProLayout.createSequentialGroup()
                .addGroup(showProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showProLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(exitD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(showProLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        showProLayout.setVerticalGroup(
            showProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showProLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitD)
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        graphPanel.setLayout(new java.awt.GridLayout(4, 4, 50, 50));

        route.setText("Start");
        route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeActionPerformed(evt);
            }
        });

        reroute.setText("Restart");
        reroute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerouteActionPerformed(evt);
            }
        });

        showState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showStateMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Yellow: wire not in use");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Red: Sink node");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Green: wire in use");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Blue: Source node");

        showInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showInfo.setText("Node Information");
        showInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("Menu");

        about.setText("About");
        jMenu1.add(about);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(showState, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reroute)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(showInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(showState, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(route)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reroute)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeActionPerformed
        // TODO add your handling code here:
        System.out.println("===============================");
        showInfo.setText("");
        ex.runIteration();
        showCong();
        graphPanel.repaint();
    }//GEN-LAST:event_routeActionPerformed

    private void rerouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerouteActionPerformed
        // TODO add your handling code here:
        ex.initialize();
        showInfo.setText("");
        showCong();
        graphPanel.repaint();
    }//GEN-LAST:event_rerouteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void showStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showStateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showStateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoutingResourceGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoutingResourceGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoutingResourceGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoutingResourceGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoutingResourceGraph().setVisible(true);
            }
        });
    }

     public void showGraph() {
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                squares[i][j] = new JToggleButton("");
                if (ex.drawGraph().get(4 * i + j).getState() == 1) {
                    squares[i][j].setText(Integer.toString(ex.drawGraph().get(4 * i + j).getKey()));
                } else if (ex.drawGraph().get(4 * i + j).getState() == 0) {
                    squares[i][j].setText(Integer.toString(ex.drawGraph().get(4 * i + j).getKey()));
                    squares[i][j].setOpaque(true);
                } else if (ex.drawGraph().get(4 * i + j).getState() == 2) {
                    squares[i][j].setText(Integer.toString(ex.drawGraph().get(4 * i + j).getKey()));
                    squares[i][j].setOpaque(true);
                }
                squares[i][j].setToolTipText("cost"+ex.drawGraph().get(4 * i + j).getCost());
                squares[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        JToggleButton l = (JToggleButton) e.getSource();
                        String state = "";
                        int num = Integer.parseInt(l.getText());
                        if (ex.drawGraph().get(num).getState() == 1) {
                            state = "wire";
                            double history_get = ex.drawGraph().get(num).getHistory();
                            int history = 0;
                            if (history_get != 0) {
                                history = (int) (Math.log(ex.drawGraph().get(num).getHistory()) / Math.log(1.1));
                            }
                            showInfo.setText("<html>" + state + "<br>" + "congestion history" + history + "<br>" + "congestion" + ex.drawGraph().get(num).getOther() + "</html>");
                        } else if (ex.drawGraph().get(num).getState() == 0) {
                            state = "source";
                            String path = "path from";
                            String cost = "cost ";
                            for (int i = 0; i < ex.drawGraph().get(num).paths.size(); i++) {
                                for (int m = 0; m < ex.drawGraph().get(num).paths.get(i).size(); m++) {
                                    path = path + " " + ex.drawGraph().get(num).paths.get(i).get(m).getKey();
                                }
                                cost = cost + ex.drawGraph().get(num).distance.get(i);
                            }                  
                            showInfo.setText("<html>" + state + "<br>" + path + "<br>" + cost +"</html>");
                        } else {
                            state = "sink";
                            showInfo.setText("state: " + state);
                        }
                    }
                });
                graphPanel.add(squares[i][j]);
            }
        }
        showInfo.setFont(new Font("Courier", Font.PLAIN, 13));
    }
     
         public void showCong() {
        if (!ex.getGraph().testCong()) {
            showState.setText("STILL CONGESTED");
        } else {
            showState.setText("This circuit has no congestion");
        }
    }
    private RunGraph ex;
    private JToggleButton squares[][];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton exitD;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea prosperity;
    private javax.swing.JButton reroute;
    private javax.swing.JButton route;
    private javax.swing.JLabel showInfo;
    private javax.swing.JDialog showPro;
    private javax.swing.JLabel showState;
    // End of variables declaration//GEN-END:variables
}
