
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import static javax.swing.SwingConstants.CENTER;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yangy
 */
public class TiledRouting extends javax.swing.JFrame {

    /**
     * Creates new form TiledRouting
     */
    public TiledRouting() {
        tile_graph = new TiledGraph(3,2);
        sources_a = new JLabel[tile_graph.getGraphSize()][tile_graph.getGraphSize()];
        sinks_a = new JLabel[tile_graph.getGraphSize()][tile_graph.getGraphSize()];
        wires_a = new JLabel[2 * tile_graph.getGraphSize() * tile_graph.getGraphSize()][2*tile_graph.getWireSize()];                
        tile_graph.initialize();
        iter = 0;
 //       setUp();
        initComponents();
        tile_graph.find_shortest_path_list();
        showCong();
//        showGraph();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        showInfo = new javax.swing.JTextArea();
        showState = new javax.swing.JLabel();
        showPanel = new DrawTile(tile_graph,showInfo);
        route = new javax.swing.JButton();
        reroute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        showSrc = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDest = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        showInfo.setBackground(new java.awt.Color(204, 204, 204));
        showInfo.setColumns(20);
        showInfo.setRows(5);
        jScrollPane2.setViewportView(showInfo);

        showPanel.setPreferredSize(new java.awt.Dimension(640, 640));

        javax.swing.GroupLayout showPanelLayout = new javax.swing.GroupLayout(showPanel);
        showPanel.setLayout(showPanelLayout);
        showPanelLayout.setHorizontalGroup(
            showPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        showPanelLayout.setVerticalGroup(
            showPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        route.setText("start");
        route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeActionPerformed(evt);
            }
        });

        reroute.setText("restart");
        reroute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerouteActionPerformed(evt);
            }
        });

        jLabel1.setText("Input net");

        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        add.setText("INPUT");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        showSrc.setColumns(20);
        showSrc.setRows(5);
        showSrc.setPreferredSize(new java.awt.Dimension(98, 94));
        jScrollPane3.setViewportView(showSrc);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        showDest.setColumns(20);
        showDest.setRows(5);
        jScrollPane1.setViewportView(showDest);

        menu.setText("Menu");

        jMenuItem1.setText("Info");
        menu.add(jMenuItem1);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        menu.add(exit);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reroute)
                                    .addComponent(route, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(showState, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addComponent(showPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showState, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(route)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reroute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(show)
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeActionPerformed
        // TODO add your handling code here:
        System.out.println("===============================");
        showInfo.setText("");
        tile_graph.runIteration();
        showNode();
        showCong();
        showPanel.removeAll();
        showPanel.revalidate();
        showPanel.repaint();
    }//GEN-LAST:event_routeActionPerformed

    private void rerouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerouteActionPerformed
        // TODO add your handling code here:
        showInfo.setText("");
        showSrc.setText("");
        showDest.setText("");
        iter = 0;
        tile_graph.initialize();
        showNode();
        showCong();
        showPanel.removeAll();
        showPanel.revalidate();
        showPanel.repaint();
    }//GEN-LAST:event_rerouteActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        tile_graph.find_shortest_path_list();
        showCong();
        showNode();
        showPanel.removeAll();
        showPanel.revalidate();
        showPanel.repaint();
    }//GEN-LAST:event_showActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        showSrc.setText("");
        showDest.setText("");
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(filename));
            String line;
            while ((line = reader.readLine()) != null) {
              String[] temp = line.split(",");
            for(int i = 1; i <temp.length;i++){
                showSrc.append(temp[0]+"\n");
                showDest.append(temp[i]+"\n");
                tile_graph.addNet(Integer.parseInt(temp[0]),Integer.parseInt(temp[i]));
              }
            }
            reader.close();
        } catch (Exception e) {
            System.err.format("Exception occurred trying to read '%s'.", filename);
            e.printStackTrace();
        }
    }//GEN-LAST:event_addActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiledRouting().setVisible(true);
            }
        });
    }

    public void setUp(){
              for (int i = 0; i < tile_graph.getGraphSize(); i++) {
            for (int j = 0; j < tile_graph.getGraphSize(); j++) {
                Tile<Integer> tile = tile_graph.getGraph()[i][j];
                int x_pos = 2 + i*640/tile_graph.getGraphSize();
                int y_pos = 2 + j*640/tile_graph.getGraphSize();
            sources_a[i][j] = new JLabel("", CENTER);
            sources_a[i][j].setText(Integer.toString(tile.getSources().get(0).getKey()));
            sources_a[i][j].setBackground(Color.green);
            sources_a[i][j].setOpaque(true);
            sources_a[i][j].setLocation(x_pos + 640/tile_graph.getGraphSize()/2 -25,y_pos+1);
            tile.getSources().get(0).pos_x_e = x_pos + 640/tile_graph.getGraphSize()/2;
            tile.getSources().get(0).pos_y_e = y_pos+1;
            sources_a[i][j].setSize(25, 25);
            sources_a[i][j].addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    JLabel l = (JLabel) e.getSource();
                    String state = "";
                    int num = Integer.parseInt(l.getText());
                    state = "source";
                    String path = "path from";
                    String cost = "cost ";
                    int key = 0;
                    for(int i = 0; i < tile_graph.getSourceList().size();i++){
                        if(tile_graph.getSourceList().get(i).getKey() == num){
                            key = i;
                        }
                    }
                                                        
                    for (int i = 0; i < tile_graph.getSourceList().get(key).paths.size(); i++) {
                        for (int m = 0; m < tile_graph.getSourceList().get(key).paths.get(i).size(); m++) {
                            path = path + " " + tile_graph.getSourceList().get(key).paths.get(i).get(m).getKey();
                        }
                        DecimalFormat numformat = new DecimalFormat("#.00");
                        cost = cost+numformat.format(tile_graph.getSourceList().get(key).distance.get(i));
                    }
                    
                    for(int i = 0; i < tile_graph.getGraphSize(); i++){
                        for(int j = 0; j < tile_graph.getGraphSize(); j++){
                            for(int k = 0; k <tile_graph.getGraph()[i][j].getSources().size();k++){
                                Tile<Integer> temp = tile_graph.getGraph()[i][j];
                                if(temp.getSources().get(k).getKey() == num){
                                    System.out.println("hello drawing");
                                }
                            }
                        }
                    }
                    showInfo.setText("<html>" + state + "<br>" + path + "<br>" + cost + "</html>");
                    
                }
            });
            sinks_a[i][j] = new JLabel("", CENTER);
            sinks_a[i][j].setText(Integer.toString(tile.getSinks().get(0).getKey()));
            sinks_a[i][j].setBackground(Color.yellow);
            sinks_a[i][j].setOpaque(true);
            sinks_a[i][j].setLocation(x_pos+1,y_pos+ 640/tile_graph.getGraphSize()/2 -25);
            tile.getSinks().get(0).pos_x_e = x_pos;
            tile.getSinks().get(0).pos_y_e = y_pos+ 640/tile_graph.getGraphSize()/2;
            sinks_a[i][j].setSize(25, 25);
            int gap_x = 0;
            int gap_y = 0;
                for (int m = 0; m < tile.getWires().size(); m++) {
                    wires_a[i * tile_graph.getGraphSize() + j][m] = new JLabel("", CENTER);
                    wires_a[i * tile_graph.getGraphSize() + j][m].setText(Integer.toString(tile.getWires().get(m).getKey()));
                    wires_a[i * tile_graph.getGraphSize() + j][m].setBackground(Color.red);
                    wires_a[i * tile_graph.getGraphSize() + j][m].setOpaque(true);
                    wires_a[i * tile_graph.getGraphSize() + j][m].addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                        JLabel l = (JLabel) e.getSource();
                        String state = "";
                        state = "wire";
                        int num = Integer.parseInt(l.getText());
                        int key = 0;
                        for(int i = 0; i < tile_graph.getSourceList().size();i++){
                           if(tile_graph.getWireList().get(i).getKey() == num){
                            key = i;
                         }
                        }
                        double history_get = tile_graph.getWireList().get(key).getHistory();
                        int history = 0;
                        if (history_get != 0) {
                        history = (int) (Math.log(tile_graph.getWireList().get(key).getHistory()) / Math.log(1.1));
                    }
                    showInfo.setText("<html>" + state +" " +num+ "<br>" + "congestion history" + history + "<br>" + "congestion" + tile_graph.getWireList().get(key).getOther() + "<br>" + "cost" + tile_graph.getWireList().get(key).getCost() +"</html>");
                }
            });
                    if(tile.getWires().get(m).dir == 0) {
                    wires_a[i * tile_graph.getGraphSize() + j][m].setLocation(x_pos + gap_x + 640/tile_graph.getGraphSize()/ 2 + 640/tile_graph.getGraphSize()/ 16, y_pos);
                    wires_a[i * tile_graph.getGraphSize() + j][m].setSize(15,640/tile_graph.getGraphSize()/ 2);    
                    tile.getWires().get(m).pos_x_s = x_pos + gap_x + 640/tile_graph.getGraphSize()/ 2 + 640/tile_graph.getGraphSize()/ 16;
                    tile.getWires().get(m).pos_y_s = y_pos;
                    tile.getWires().get(m).pos_x_e = x_pos + gap_x + 640/tile_graph.getGraphSize()/ 2 + 640/tile_graph.getGraphSize()/ 16;
                    tile.getWires().get(m).pos_y_e = y_pos + 640/tile_graph.getGraphSize()/ 2;
                    gap_x = gap_x + 640/tile_graph.getGraphSize()/ 4;
                    }
                    else{
                    wires_a[i * tile_graph.getGraphSize() + j][m].setLocation(x_pos, y_pos+ gap_y +640/tile_graph.getGraphSize()/ 2 + 640/tile_graph.getGraphSize()/ 16);
                    wires_a[i * tile_graph.getGraphSize() + j][m].setSize(640/tile_graph.getGraphSize()/ 2, 15);
                    tile.getWires().get(m).pos_x_s = x_pos;
                    tile.getWires().get(m).pos_y_s = y_pos+ gap_y +640/tile_graph.getGraphSize()/ 2 + 640/tile_graph.getGraphSize()/ 16;
                    tile.getWires().get(m).pos_x_e = x_pos +640/tile_graph.getGraphSize()/ 2;
                    tile.getWires().get(m).pos_y_e = y_pos+ gap_y +640/tile_graph.getGraphSize()/ 2 + 640/tile_graph.getGraphSize()/ 16;
                    gap_y = gap_y + 640/tile_graph.getGraphSize()/ 4;
                    }
                }
            }
        }
    }
    public void showGraph(){
        for (int i = 0; i < tile_graph.getGraphSize(); i++) {
            for (int j = 0; j < tile_graph.getGraphSize(); j++) {
                Tile<Integer> tile = tile_graph.getGraph()[i][j];
            showPanel.add(sources_a[i][j]);
            showPanel.add(sinks_a[i][j]);
                for (int m = 0; m < tile.getWires().size(); m++) {
                    showPanel.add(wires_a[i * tile_graph.getGraphSize() + j][m]);
                }
            }
        }
        showInfo.setFont(new Font("Courier", Font.PLAIN, 13)); 
    }
    
    
    public void showCong() {
        if (!tile_graph.testCong()) {
            iter++;
            showState.setText("STILL CONGESTED");
        } else {
            showState.setText("This circuit has no congestion");
            showInfo.append("iteration number: " + iter);
            iter = 0;
        }
    }
    
    public void showNode(){
        showInfo.setText("");
        for(int i = 0; i < tile_graph.getGraphSize(); i++){
            for(int j = 0; j < tile_graph.getGraphSize(); j++){
                Tile<Integer> temp = tile_graph.getGraph()[i][j];
                for(int k = 0; k < temp.getWires().size();k++){
                    if(temp.getWires().get(k).getOther() > 2){
                        DecimalFormat numformat = new DecimalFormat("#.00");
                        showInfo.append("show node: " +temp.getWires().get(k).getKey() + "\n" +"show cost: " + numformat.format(temp.getWires().get(k).getCost()) +"\n"+ "congestion" + temp.getWires().get(k).getOther()+"\n");
                    }
                }
            }
        }
    }

    TiledGraph tile_graph;
    private JLabel sources_a[][];
    private JLabel sinks_a[][];
    private JLabel wires_a[][];
    private int iter;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu menu;
    private javax.swing.JButton reroute;
    private javax.swing.JButton route;
    private javax.swing.JButton show;
    private javax.swing.JTextArea showDest;
    private javax.swing.JTextArea showInfo;
    private javax.swing.JPanel showPanel;
    private javax.swing.JTextArea showSrc;
    private javax.swing.JLabel showState;
    // End of variables declaration//GEN-END:variables
}
