
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yangy
 */
public class TiledRouting extends javax.swing.JFrame {

    /**
     * Creates new form TiledRouting
     */
    int run_num = 0;
    Timer timer = new Timer(400, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) {
            //...Perform a task...
            if(run_num < Integer.parseInt(num_field.getText())) {
                run_num++;
                System.out.println("===============================");
                showInfo.setText("");
                tile_graph.runIteration();
                showNode();
                if(showCong()) run_num = Integer.parseInt(num_field.getText());
                showPanel.removeAll();
                showPanel.revalidate();
                showPanel.repaint();
            }
            else{
                Timer tim = (Timer) evt.getSource();
                tim.stop();
                run_num = 0;
            }
        }
    });
    
    public TiledRouting() {
        tile_graph = new TiledGraph(8,2);
        sources_a = new JLabel[tile_graph.getGraphSize()][tile_graph.getGraphSize()];
        sinks_a = new JLabel[tile_graph.getGraphSize()][tile_graph.getGraphSize()];
        wires_a = new JLabel[2 * tile_graph.getGraphSize() * tile_graph.getGraphSize()][2*tile_graph.getWireSize()];                
        tile_graph.initialize();
        iter = 0;
        setUp();
        initComponents();
        tile_graph.find_shortest_path_list();
        showCong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        showInfo = new javax.swing.JTextArea();
        showState = new javax.swing.JLabel();
        showPanel = new DrawTile(tile_graph,showInfo,sources_a,sinks_a,wires_a);
        route = new javax.swing.JButton();
        reroute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        showSrc = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDest = new javax.swing.JTextArea();
        num_field = new javax.swing.JTextField();
        stopr = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showInfo.setBackground(new java.awt.Color(204, 204, 204));
        showInfo.setColumns(20);
        showInfo.setRows(5);
        jScrollPane2.setViewportView(showInfo);

        showPanel.setPreferredSize(new java.awt.Dimension(640, 640));

        javax.swing.GroupLayout showPanelLayout = new javax.swing.GroupLayout(showPanel);
        showPanel.setLayout(showPanelLayout);
        showPanelLayout.setHorizontalGroup(
            showPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        showPanelLayout.setVerticalGroup(
            showPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        route.setText("start");
        route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeActionPerformed(evt);
            }
        });

        reroute.setText("restart");
        reroute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerouteActionPerformed(evt);
            }
        });

        jLabel1.setText("Input net");

        show.setText("SHOW");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        add.setText("INPUT");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        showSrc.setColumns(20);
        showSrc.setRows(5);
        showSrc.setPreferredSize(new java.awt.Dimension(98, 94));
        jScrollPane3.setViewportView(showSrc);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        showDest.setColumns(20);
        showDest.setRows(5);
        jScrollPane1.setViewportView(showDest);

        stopr.setText("stop");
        stopr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoprActionPerformed(evt);
            }
        });

        menu.setText("Menu");

        jMenuItem1.setText("Info");
        menu.add(jMenuItem1);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        menu.add(exit);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(246, 246, 246))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(showState, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(route, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(stopr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reroute)
                                    .addComponent(num_field, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(showPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showState, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(route)
                            .addComponent(num_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reroute)
                            .addComponent(stopr))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(show)
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeActionPerformed
        if(restart)    {
            setUp();
            tile_graph.find_shortest_path_list();
            restart = false;
        }  
        timer.start();
    }//GEN-LAST:event_routeActionPerformed

    private void rerouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerouteActionPerformed
        // TODO add your handling code here:
        showInfo.setText("");
        showSrc.setText("");
        showDest.setText("");
        iter = 0;
        tile_graph.initialize();
        restart = true;
        showNode();
        showCong();
        showPanel.removeAll();
        showPanel.revalidate();
        showPanel.repaint();
    }//GEN-LAST:event_rerouteActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        tile_graph.find_shortest_path_list();
        showCong();
        showNode();
        showPanel.removeAll();
        showPanel.revalidate();
        showPanel.repaint();
    }//GEN-LAST:event_showActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        showSrc.setText("");
        showDest.setText("");
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(filename));
            String line;
            while ((line = reader.readLine()) != null) {
              String[] temp = line.split(",");
            for(int i = 1; i <temp.length;i++){
                showSrc.append(temp[0]+"\n");
                showDest.append(temp[i]+"\n");
                tile_graph.addNet(Integer.parseInt(temp[0]),Integer.parseInt(temp[i]));
              }
            }
            reader.close();
        } catch (Exception e) {
            System.err.format("Exception occurred trying to read '%s'.", filename);
            e.printStackTrace();
        }
    }//GEN-LAST:event_addActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void stoprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoprActionPerformed
        // TODO add your handling code here:
        timer.stop();
    }//GEN-LAST:event_stoprActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiledRouting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiledRouting().setVisible(true);
            }
        });
    }

 public void setUp() {
        for (int i = 0; i < tile_graph.getGraphSize(); i++) {
            for (int j = 0; j < tile_graph.getGraphSize(); j++) {
                Tile<Integer> tile = tile_graph.getGraph()[i][j];
                int x_pos = 2 + i * drawBorder / tile_graph.getGraphSize();
                int y_pos = 2 + j * drawBorder / tile_graph.getGraphSize();
                sources_a[i][j] = new JLabel("", CENTER);
                sources_a[i][j].setText(Integer.toString(tile.getSources().get(0).getKey()));
                sources_a[i][j].setBackground(Color.green);
                sources_a[i][j].setOpaque(true);
                sources_a[i][j].setLocation(x_pos + drawBorder / tile_graph.getGraphSize() / 2 - drawBorder / tile_graph.getGraphSize()/8, y_pos + 1);
                tile.getSources().get(0).pos_x_e = x_pos + drawBorder / tile_graph.getGraphSize() / 2;
                tile.getSources().get(0).pos_y_e = y_pos + 1;
                sources_a[i][j].setSize(drawBorder / tile_graph.getGraphSize() /8, drawBorder / tile_graph.getGraphSize()/8);
                sources_a[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        JLabel l = (JLabel) e.getSource();
                        showInfo.setText("");
                        String state = "";
                        int num = Integer.parseInt(l.getText());
                        state = "source";
                        String path = "path from";
                        String cost = "cost ";
                        int key = 0;
                        for (int i = 0; i < tile_graph.getSourceList().size(); i++) {
                            if (tile_graph.getSourceList().get(i).getKey() == num) {
                                key = i;
                            }
                        }

                        for (int i = 0; i < tile_graph.getSourceList().get(key).paths.size(); i++) {
                            path = "path from";
                            cost = "cost";
                            for (int m = 0; m < tile_graph.getSourceList().get(key).paths.get(i).size(); m++) {
                                path = path + " " + tile_graph.getSourceList().get(key).paths.get(i).get(m).getKey();
                            }
                            DecimalFormat numformat = new DecimalFormat("#.00");
                            cost = cost + numformat.format(tile_graph.getSourceList().get(key).distance.get(i));
                            showInfo.append(state + "\n" + path + "\n" + cost + "!" + "\n");
                        }

                        for (int i = 0; i < tile_graph.getGraphSize(); i++) {
                            for (int j = 0; j < tile_graph.getGraphSize(); j++) {
                                for (int k = 0; k < tile_graph.getGraph()[i][j].getSources().size(); k++) {
                                    Tile<Integer> temp = tile_graph.getGraph()[i][j];
                                    if (temp.getSources().get(k).getKey() == num) {
                                        System.out.println("hello drawing");

                                    }
                                }
                            }
                        }

                    }
                });
                sinks_a[i][j] = new JLabel("", CENTER);
                sinks_a[i][j].setText(Integer.toString(tile.getSinks().get(0).getKey()));
                sinks_a[i][j].setBackground(Color.green);
                sinks_a[i][j].setOpaque(true);
                sinks_a[i][j].setLocation(x_pos + 1, y_pos + drawBorder / tile_graph.getGraphSize() / 2 - drawBorder / tile_graph.getGraphSize() /8);
                tile.getSinks().get(0).pos_x_e = x_pos;
                tile.getSinks().get(0).pos_y_e = y_pos + drawBorder / tile_graph.getGraphSize() / 2;
                sinks_a[i][j].setSize(drawBorder/ tile_graph.getGraphSize() /8, drawBorder / tile_graph.getGraphSize() /8);
                int gap_x = 0;
                int gap_y = 0;
                for (int m = 0; m < tile.getWires().size(); m++) {
                    wires_a[i * tile_graph.getGraphSize() + j][m] = new JLabel("", CENTER);
                    wires_a[i * tile_graph.getGraphSize() + j][m].setText(Integer.toString(tile.getWires().get(m).getKey()));
                    int rc = (int)tile.getWires().get(m).getCost();
                    int gc = (int)tile.getWires().get(m).getCost()*10;
                    int bc = 255-(int)tile.getWires().get(m).getCost();
                    if (rc > 255) rc = 255;
                    if (gc > 255) gc = 255;
                    if (bc < 0)     bc = 0;
                    wires_a[i * tile_graph.getGraphSize() + j][m].setBackground(new Color(rc,gc,bc));
                    wires_a[i * tile_graph.getGraphSize() + j][m].setOpaque(true);
                    wires_a[i * tile_graph.getGraphSize() + j][m].addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            JLabel l = (JLabel) e.getSource();
                            String state = "";
                            state = "wire";
                            int num = Integer.parseInt(l.getText());
                            int key = 0;
                            for (int i = 0; i < tile_graph.getWireList().size(); i++) {
                                if (tile_graph.getWireList().get(i).getKey() == num) {
                                    key = i;
                                }
                            }
                            double history_get = tile_graph.getWireList().get(key).getHistory();
                            int history = 0;
                            if (history_get != 0) {
                                history = (int) (Math.log(tile_graph.getWireList().get(key).getHistory()) / Math.log(1.1));
                            }
                            DecimalFormat numformat = new DecimalFormat("#.00");
                            showInfo.setText(state + " " + num + "\n" + "congestion history" + history + "\n" + "congestion" + tile_graph.getWireList().get(key).getOther() + "\n" + "cost" +numformat.format(tile_graph.getWireList().get(key).getCost())  + "");
                        }
                    });
                    if (tile.getWires().get(m).dir == 0) {
                        wires_a[i * tile_graph.getGraphSize() + j][m].setLocation(x_pos + gap_x + drawBorder / tile_graph.getGraphSize() / 2 + drawBorder / tile_graph.getGraphSize() / 16, y_pos);
                        wires_a[i * tile_graph.getGraphSize() + j][m].setSize(drawBorder / tile_graph.getGraphSize() / 8/(tile_graph.getWireSize()-1), drawBorder / tile_graph.getGraphSize() / 2);
                        tile.getWires().get(m).pos_x_s = x_pos + gap_x + drawBorder / tile_graph.getGraphSize() / 2 + drawBorder / tile_graph.getGraphSize() / 16;
                        tile.getWires().get(m).pos_y_s = y_pos;
                        tile.getWires().get(m).pos_x_e = x_pos + gap_x + drawBorder / tile_graph.getGraphSize() / 2 + drawBorder / tile_graph.getGraphSize() / 16;
                        tile.getWires().get(m).pos_y_e = y_pos + drawBorder / tile_graph.getGraphSize() / 2;
                        gap_x = gap_x + drawBorder / tile_graph.getGraphSize() / 4/(tile_graph.getWireSize()-1);
                    } else {
                        wires_a[i * tile_graph.getGraphSize() + j][m].setLocation(x_pos, y_pos + gap_y + drawBorder / tile_graph.getGraphSize() / 2 + drawBorder / tile_graph.getGraphSize() / 16);
                        wires_a[i * tile_graph.getGraphSize() + j][m].setSize(drawBorder / tile_graph.getGraphSize() / 2, drawBorder / tile_graph.getGraphSize() / 8/(tile_graph.getWireSize()-1));
                        tile.getWires().get(m).pos_x_s = x_pos;
                        tile.getWires().get(m).pos_y_s = y_pos + gap_y + drawBorder / tile_graph.getGraphSize() / 2 + drawBorder / tile_graph.getGraphSize() / 16;
                        tile.getWires().get(m).pos_x_e = x_pos + drawBorder / tile_graph.getGraphSize() / 2;
                        tile.getWires().get(m).pos_y_e = y_pos + gap_y + drawBorder /tile_graph.getGraphSize() / 2 + drawBorder / tile_graph.getGraphSize() / 16;
                        gap_y = gap_y + drawBorder / tile_graph.getGraphSize() / 4/(tile_graph.getWireSize()-1);
                    }
                }
            }
        }
    }
    
 public boolean showCong() {
        if (!tile_graph.testCong()) {
            iter++;
            showState.setText("STILL CONGESTED");
            return false;
        } else {
            showState.setText("This circuit has no congestion");
            showInfo.append("iteration number: " + iter);
            iter = 0;
            return true;
        }
    }
    
 public void showNode(){
        showInfo.setText("");
        for(int i = 0; i < tile_graph.getGraphSize(); i++){
            for(int j = 0; j < tile_graph.getGraphSize(); j++){
                Tile<Integer> temp = tile_graph.getGraph()[i][j];
                for(int k = 0; k < temp.getWires().size();k++){
                    if(temp.getWires().get(k).getOther() > 2){
                        DecimalFormat numformat = new DecimalFormat("#.00");
                        showInfo.append("show node: " +temp.getWires().get(k).getKey() + "\n" +"show cost: " + numformat.format(temp.getWires().get(k).getCost()) +"\n"+ "congestion" + temp.getWires().get(k).getOther()+"\n");
                    }
                }
            }
        }
    }


    TiledGraph tile_graph;
    private JLabel sources_a[][];
    private JLabel sinks_a[][];
    private JLabel wires_a[][];
    private int iter;
    private boolean restart = false;
    private final int drawBorder = 640;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField num_field;
    private javax.swing.JButton reroute;
    private javax.swing.JButton route;
    private javax.swing.JButton show;
    private javax.swing.JTextArea showDest;
    private javax.swing.JTextArea showInfo;
    private javax.swing.JPanel showPanel;
    private javax.swing.JTextArea showSrc;
    private javax.swing.JLabel showState;
    private javax.swing.JButton stopr;
    // End of variables declaration//GEN-END:variables
}
